### ISSUE TITLE
Let's make this a multi-arch image, so everyone on every Docker platform can run and use it. 

### ISSUE THREAD

**Issue by vielmetti** [estesp/mquery#1]
As suggested by Stefan, let's build and distribute this so that it's a multi-arch image.

(Not only would it be useful, but it would be a good template for building and distributing multiarch Go applications.)

**Comment by estesp** [comment]
Thanks to @StefanScherer and his good work in PR #3 this is now complete:

Almost inception-like, but proof below :)
```
$ docker run --rm mplatform/mquery mplatform/mquery
Manifest List: Yes
Supported platforms:
 - amd64/linux
 - arm/linux (variant: undefined)
 - arm64/linux (variant: undefined)
 - ppc64le/linux
 - s390x/linux
 - amd64/windows
```

**Comment by StefanScherer** [comment]
I think we could annotate the arm/arm64 variant as well. Thanks @estesp for merging!

**Comment by estesp** [comment]
Agree; was going to create a yaml for `manifest-tool` to handle the variants.. I should probably fix `make cross` to actually use `GOARM` to be explicit as well
