### ISSUE TITLE
riscv architecture support?

### ISSUE THREAD

**Issue by olof-nord** [estesp/mquery#19]
I am wondering if this project would like to support the riscv architecture.

RISC-V is an open standard instruction set architecture (ISA) based on established reduced instruction set computer (RISC) principles. Unlike most other ISA designs, the RISC-V ISA is provided under open source licenses that do not require fees to use. (from Wikipedia)

Golang supports cross-compiling risc-v already (GOARCH=riscv64/GOOS=linux), and looking into this project I think adding a new architecture would be quite achievable.

As an early riscv docker user, most if not all docker images does not support riscv yet, and being able to run this tool from a riscv docker system would be great to know what arch is supported and what is not.

**Comment by olof-nord** [comment]
To clarify with supporting: to build and publish a docker image which can be executed on a riscv system.

Current image does not support linux/riscv:

```log
$ docker run --rm mplatform/mquery debian:bullseye      
Unable to find image 'mplatform/mquery:latest' locally
latest: Pulling from mplatform/mquery
docker: no matching manifest for linux/riscv64 in the manifest list entries.
See 'docker run --help'.
```

**Comment by estesp** [comment]
Looks like that was a pretty easy addition via #22; I'm going to test with a quick pre-release (that doesn't change the ":latest" tag for mquery) and probably will ask you to verify it since I don't have access to risc-v hardware :) Once we do that, then I can make a non-pre-release and it should work out of the box for risc-v.

**Comment by estesp** [comment]
@olof-nord would you mind trying the v0.5.0-rc.0 image to make sure it works?

It shows that it should support riscv now:
```
$ ./mquery-linux-amd64 mplatform/mquery:v0.5.0-rc.0
Image: mplatform/mquery:v0.5.0-rc.0 (digest: sha256:56c902130c84951b157b43bc4ebf9b48e11a856adee214325d0df8cfbaa342c7)
 * Manifest List: Yes (Image type: application/vnd.docker.distribution.manifest.list.v2+json)
 * Supported platforms:
   - linux/ppc64le
   - linux/amd64
   - linux/386
   - linux/s390x
   - linux/riscv64
   - linux/arm64/v8
   - linux/arm/v7
   - linux/arm/v6
   - windows/amd64:10.0.17763.2300
   - windows/amd64:10.0.14393.4770
```

You should be able to verify on riscv by running:
```
$ {whateverruntime} run mplatform/mquery:v0.5.0-rc.0 {someotherimage}
```

**Comment by olof-nord** [comment]
Of course, and I can report success!

Many thanks for this, I really appreciate it.

```log
➜  ~ uname -a                                                    
Linux c-3po 5.13.0-1006-generic #6-Ubuntu SMP Thu Nov 11 10:33:30 UTC 2021 riscv64 riscv64 riscv64 GNU/Linux
➜  ~ docker run --rm mplatform/mquery:v0.5.0-rc.0 debian:bullseye
Image: debian:bullseye (digest: sha256:45ee40a844048c2f6d0105899c1a17733530b56d481612608aab5e2e4048570b)
 * Manifest List: Yes (Image type: application/vnd.docker.distribution.manifest.list.v2+json)
 * Supported platforms:
   - linux/amd64
   - linux/arm/v5
   - linux/arm/v7
   - linux/arm64/v8
   - linux/386
   - linux/mips64le
   - linux/ppc64le
   - linux/s390x
➜  ~
```

**Comment by estesp** [comment]
Great! I tagged `v0.5.0` this morning and pushed, so now the default `mplatform/mquery` image has the riscv support included. Thanks for suggesting the update and testing it!

Release: https://github.com/estesp/mquery/releases/tag/v0.5.0
